[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.mainnet]
solana_coinflip_game = "6MNUPzTs5MMGNrvnCdGyMDJ6mH7ciE3MyzbaeYGwdQxi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/Users/atlas-ryan/.config/solana/new-mainnet-deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
