[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_coinflip_game = "HLTBPRZKvKxtRHg6gyBGfu1XodqWeAWu3wd2Sc7jsHyf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/mainnet-deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"